CREATE DATABASE "proyectoBD"
    WITH
    OWNER = root
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;


CREATE TABLE USUARIO (CVE_USUARIO SERIAL PRIMARY KEY, NOMBRE_USUARIO VARCHAR(30) NOT NULL,
APELLIDO_USUARIO VARCHAR(30), EMAIL_USUARIO VARCHAR(30) NOT NULL, CONTRASENIA_USUARIO VARCHAR(20),
TIPO_USUARIO INT);

CREATE TABLE GENERO(CVE_GENERO SERIAL PRIMARY KEY, DESCRIPCION_GENERO VARCHAR(25));
CREATE TABLE DIRECTOR(CVE_DIRECTOR SERIAL PRIMARY KEY, NOMBRE_DIRECTOR VARCHAR(40), PAIS_DIRECTOR VARCHAR(20));
CREATE TABLE ACTORPRINCIPAL(CVE_ACTOR SERIAL PRIMARY KEY, NOMBRE_ACTOR VARCHAR(40), PAIS_ACTOR VARCHAR(20));
CREATE TABLE SERIE(CVE_SERIE SERIAL PRIMARY KEY, TITULO_SERIE VARCHAR(50) NOT NULL, ANIO_SERIE INT NOT NULL,
TEMPORADAS INT NOT NULL, PAIS_SERIE VARCHAR(20), PORTADA_SERIE VARCHAR NOT NULL, SINOPSIS_SERIE VARCHAR(500),
CVE_DIRECTOR INT REFERENCES DIRECTOR(CVE_DIRECTOR), CVE_ACTOR INT REFERENCES ACTORPRINCIPAL(CVE_ACTOR),
CVE_GENERO INT REFERENCES GENERO(CVE_GENERO));
CREATE TABLE USUARIO_SERIE(CVE_USUARIO INT REFERENCES USUARIO(CVE_USUARIO), CVE_SERIE INT REFERENCES SERIE(CVE_SERIE),
CALIFICACION INT);


CREATE VIEW VIEW_SERIES AS
Select SERIE.CVE_SERIE, SERIE.TITULO_SERIE,SERIE.ANIO_SERIE,SERIE.TEMPORADAS,
SERIE.PAIS_SERIE,SERIE.PORTADA_SERIE,SERIE.SINOPSIS_SERIE,
ACTORPRINCIPAL.NOMBRE_ACTOR, GENERO.DESCRIPCION_GENERO,
DIRECTOR.NOMBRE_DIRECTOR from SERIE
INNER JOIN GENERO ON GENERO.CVE_GENERO = SERIE.CVE_GENERO
INNER JOIN DIRECTOR ON DIRECTOR.CVE_DIRECTOR = SERIE.CVE_DIRECTOR
INNER JOIN ACTORPRINCIPAL ON ACTORPRINCIPAL.CVE_ACTOR = SERIE.CVE_ACTOR;
